### ISSUE TITLE
When Exiting AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException: -1

### ISSUE THREAD

**Issue by theaaron123** [theaaron123/dungeonsgame#6]
When you exit the game an exception AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException: -1 may be thrown due to `if (dg.gridBounds[dg.player.getPlayerY()][dg.player.getPlayerX() -1] == 1)` in DungeonView line 99 [99](https://github.com/theaaron123/dungeonsgame/blob/94b94a3cf0236fa3d037b4580d2b6acc3fdc716a/src/main/java/DungeonView.java#L99) and several other places in that class

**Comment by jk370** [comment]
Issue prevented from occurring by not allowing movement onto exit until enough Gold is acquired. Dungeon is reset once this happens.
