### ISSUE TITLE
checkExit always returns true

### ISSUE THREAD

**Issue by theaaron123** [theaaron123/dungeonsgame#9]
This method always returns true [here](https://github.com/theaaron123/dungeonsgame/blob/1acc061698b80b41cc845faddfb4ebe177ebdff7/src/main/java/uk/ac/bath/se/DungeonController.java#L239)

**Comment by MarcAdlington** [comment]
will amend this

**Comment by jk370** [comment]
I fixed this in my last push of the player-score branch, but have just made another amendment. It seems to be working fine.
